### ISSUE TITLE
Wallet startup failure...

### ISSUE THREAD

**Issue by mtl1979** [valiant1x/intensecoinwallet#10]
When the GUI wallet is started and it fails due to non-fatal error, for example daemon is running but internal daemon is selected in settings, the error dialog is hidden behind the splash screen and can't be dismissed. It's impossible to minimize the splash screen as the error dialog is modal dialog and thus the splash screen doesn't get any mouse events.

**Comment by valiant1x** [comment]
fixed in a0eb81278a4e7e57bd9e48dd61d0d1c9685b639c
