### ISSUE TITLE
Blockchain Load Error - MacOS

### ISSUE THREAD

**Issue by Nova8** [valiant1x/intensecoinwallet#11]
Anyone know how to solve this issue, I would be grateful, I have searched hidden files can't find anything to solve this problem. 

This happened wile block synchronisation was active 43 days to be exact. when closed then reopened.

**Comment by valiant1x** [comment]
Blockchain load error indicates data corruption, which is usually from a power outage or other abnormal shutdown. To prevent this issue in the future, avoid losing power while the wallet is running, and avoid abrupt/forced shutdown of the Intensecoin wallet. To resolve the issue as it exists, clear the blocks.bin file from the data directory `~/.intensecoin`. If the issue persists, delete any files in the data directory that do not end in `.wallet`.
