### ISSUE TITLE
Different Balance in Wallet Backup

### ISSUE THREAD

**Issue by CoinLogik** [valiant1x/intensecoinwallet#12]
Default wallet (stored in `~/.intensecoin`) shows balance of 187.38. I backed up the wallet and loaded the backup and balance shows e.g. 79.73. I then re-loaded wallet from `~/.intensecoin` and balance shows 187.38.

Bottom left of GUI shows "Wallet synchronized".

![image](https://user-images.githubusercontent.com/34975638/34459198-d722a848-edb6-11e7-94d9-dc46cd3b9787.png)

**Comment by CoinLogik** [comment]
Anyone able to help?  @valiant1x @cryptonotefoundation

**Comment by valiant1x** [comment]
CoinLogik, at times the .wallet file becomes out of sync with the blockchain, especially if you are using the same .wallet file in multiple places as it may be unaware of transactions made in the other wallet. Use `File > Reset wallet` to resolve.
