### ISSUE TITLE
Issue compiling (rocksdb.lib)

### ISSUE THREAD

**Issue by luiscosio** [valiant1x/intensecoinwallet#14]
6>LINK : fatal error LNK1181: cannot open input file 'rocksdb.lib'

**Comment by valiant1x** [comment]
rocksdb is failing to compile, please try compiling that project first

**Comment by luiscosio** [comment]
Re-builded everything.

cmake.exe -DBOOST_ROOT=C:\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\boost_1_59_0\libs\ -DCMAKE_PREFIX_PATH=D:\Qt\5.10.0\msvc2015_64 -G "Visual Studio 14 Win64" ..

Then opened the .snl in Visual Studio 2015, compiled and everything worked like a charm,
