### ISSUE TITLE
Mining App does not show work completed to date.

### ISSUE THREAD

**Issue by InMyImage** [valiant1x/intensecoinwallet#17]
When using the  Intensecoin-linux-x86_64.AppImage there is not any indication of work completed or a running total of earned coins or paid coins.

**Comment by valiant1x** [comment]
If you're referring to in-wallet mining, did you check the 'Mining' tab? Is it zero'd out?

**Comment by InMyImage** [comment]
Yes, and actually just discovered that when restarting mining (at least after closing the app and restarting it) it does not show hashes completed to date, just for that session.

The only values that appear on the Mining page are:
Pool, Difficulty, Good shares, Bad shares, Connection Errors and Last Connection Error.

There are no fields to show hashes completed in total for all mining sessions, pending coins/fractional coins due/unpaid or coins paid. All of which should be available in total for all mining sessions.

I've only used hashvault.pro to mine, but looked at a couple of other pools and they all appear to provide data similar to that.

Right now, using the Intense Wallet to mine I have no idea how many coins/fractional coins are pending and what's been paid.

I'm definitely interested in seeing this data so that I can compare the performance of the Intense pool vs hashvault to see if I might want to use the wallet mining long term.

**Comment by valiant1x** [comment]
None of this data is provided in-wallet by default due to a lack of standardized APIs across pool software. To view pool mining stats you will need to visit the respective pool website and input your wallet address. The only pool added by default in the GUI wallet is intensecoin.com/pool
