### ISSUE TITLE
Intensecoin cannot be opened because of a problem.

### ISSUE THREAD

**Issue by zhmrab** [valiant1x/intensecoinwallet#19]
Getting this on MacOS High Sierra, think there might be a problem with the app

Check with the developer to make sure Intensecoin works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Click Report to see more detailed information and send a report to Apple.

...

**Comment by zhmrab** [comment]
When compiling from source it works on my mac then I tried on another mac and same message comes back? Ideas?

**Comment by InMyImage** [comment]
Did you try using the Intensecoin-mac.dmg ?

I used that precompiled version and it works on my Mac although I'm on Sierra (10.12.6) vs High Sierra.

**Comment by zhmrab** [comment]
@InMyImage I did try it and it gave me the same error, on High Sierra. Now trying to build it through xcode see if I can get rid of this bug, I'll document the progress and the changes made

**Comment by zhmrab** [comment]
@valiant1x how do I compile intensecoinwallet on Mac with the libraries & plugins it needs so that it will work as a .dmg on other computers?

so far with cmake & make it works on my computer but not on other computers... Thanks!

**Comment by InMyImage** [comment]
Thanks @zhmrab

Keep getting the really PITA nag notification to uptade from Sierra to High Sierra and this issue will make me wait until it is resolved

Have a good weekend

**Comment by valiant1x** [comment]
resolved in [latest release](https://github.com/valiant1x/intensecoinwallet/releases/tag/v1.5-beta3)
