### ISSUE TITLE
Incorrect status bar on fast blocks

### ISSUE THREAD

**Issue by AzzieElbub** [valiant1x/intensecoinwallet#2]
A minor glitch.
When the blocks are mined very quickly (several seconds) the status bar at the bottom reading "Synchronization: xxx/yyy (zz hours nn minutes)"
is reading incorrect time, very large value such is 239582958239058 hours (value made up, not actual).

**Comment by valiant1x** [comment]
We have very fast blocks now and I'm still not able to replicate this issue. Perhaps it was only occurring in an early version of the software? There were some adjustments made to the code determining status bar displays earlier on in the development cycle, although it wasn't explicitly labeled under a useful commit name. For now, I will close this issue. If you see it again, please re-open and let me know which OS/environment you are seeing it on.
