### ISSUE TITLE
Intensecoin.exe unable to start with scandinavian letters in user account name

### ISSUE THREAD

**Issue by Monkeybrain73** [valiant1x/intensecoinwallet#22]
The wallet hangs on startup if the useraccount has any scandinavian letter in them. Ææ, Øø , Åå.

Replicated by testing on different accounts on the same computer.
Works fine on accounts that do not have scandinavian letters in them.

**Comment by valiant1x** [comment]
issue is occurring in pre-rebase GUI. please switch to the newest available release download as prior versions will no longer be supported.
