### ISSUE TITLE
Note: the wallet does not compile on Raspberry pi.

### ISSUE THREAD

**Issue by manzikki** [valiant1x/intensecoinwallet#24]
crypto/slow-hash.c wants some include files that are not available for ARM. You may want to have a build option OMIT_MINER (Pi is too slow for mining anyway) or similar.

**Comment by valiant1x** [comment]
the [xmr](https://github.com/valiant1x/intensecoinwallet/tree/xmr) branch (which will be merged into master in the near future) compiles properly for ARM.
