### ISSUE TITLE
Compilation fails on linux

### ISSUE THREAD

**Issue by mtompkins** [valiant1x/intensecoinwallet#36]
```
...
CMake Error at cryptonote/external/db_drivers/liblmdb/CMakeLists.txt:53 (if):
if given arguments:

   "EQUAL" "32"

Unknown arguments specified
```

The AppImage is now out of date with `fontconfig` and users will start to report problems / unable to start:

```
LD_LIBRARY_PATH=. QT_DEBUG_PLUGINS=1 ./Intensecoin-linux-x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_IntensPhv5L7/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_IntensPhv5L7/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_IntensPhv5L7/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329985
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_IntensPhv5L7/platforms" ...
Cannot load library /tmp/.mount_IntensPhv5L7/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)
QLibraryPrivate::loadPlugin failed on "/tmp/.mount_IntensPhv5L7/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_IntensPhv5L7/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by mbatini** [comment]
My info on issue:

Ubuntu 17.10 updated

uname -a
Linux mb460 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

dpkg -l|grep unboun
ii  libunbound-dev:amd64                       1.6.5-1ubuntu0.1                                           amd64        static library, header files, and docs for libunbound
ii  libunbound2:amd64                          1.6.5-1ubuntu0.1                                           amd64        library implementing DNS resolution and validation

dpkg -l|grep miniup
ii  libminiupnpc-dev                           1.9.20140610-4ubuntu1.1                                    amd64        UPnP IGD client lightweight library development files
ii  libminiupnpc10:amd64                       1.9.20140610-4ubuntu1.1                                    amd64        UPnP IGD client lightweight library

sudo cmake -DSTATIC=1 ..
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Using miniupnpc from local source tree for static build
CMake Warning at cryptonote/external/CMakeLists.txt:74 (find_package):
  By not providing "FindUnbound.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Unbound", but
  CMake did not find one.

  Could not find a package configuration file provided by "Unbound" with any
  of the following names:

    UnboundConfig.cmake
    unbound-config.cmake

  Add the installation prefix of "Unbound" to CMAKE_PREFIX_PATH or set
  "Unbound_DIR" to a directory containing one of the above files.  If
  "Unbound" provides a separate development package or SDK, be sure it has
  been installed.


-- Using -bit LMDB from source tree
CMake Error at cryptonote/external/db_drivers/liblmdb/CMakeLists.txt:53 (if):
  if given arguments:

    "EQUAL" "32"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/opt/intense-monero/intensecoinwallet/build/CMakeFiles/CMakeOutput.log".
See also "/opt/intense-monero/intensecoinwallet/build/CMakeFiles/CMakeError.log".

**Comment by mtompkins** [comment]
Nothing since January. Dead project.

**Comment by pallas1** [comment]
@mtompkins if you look at the xmr branch you will see where all the work is going on.

**Comment by mtompkins** [comment]
Fair enough - I spoke without looking at other branches. Still disappointing there's little movement on the master.

**Comment by iedemam** [comment]
To be clear, these errors are against the master branch, correct?

Have you tried building the XMR branch (where development it taking place)? After checking out that branch, make sure to follow the appropriate readme: https://github.com/valiant1x/intensecoinwallet/blob/xmr/README.md

**Comment by mtompkins** [comment]
@iedemam Yes, in my case I've only been working with the master branch. I'll try the XMR branch and revert/confirm.

**Comment by iedemam** [comment]
@mtompkins ok, thanks for the confirmation. We're going to merge XMR to master in the near future but for now it's still staged in a development branch.

**Comment by mbatini** [comment]
Ok, from xmr branch I can compile (with a lot of qt dependencies added) on Ubuntu 17.10 64bit. Now I will try to use old intensecoin.wallet.

Thanks!

**Comment by valiant1x** [comment]
@mbatini previous wallet versions are incompatible with 1.45 and above, please see [reddit for a guide to  converting your wallet files](https://www.reddit.com/r/IntenseCoin/comments/89gw15/guide_converting_your_141142_wallet_to_the_145/)
