### ISSUE TITLE
Error launching wallet after compilation (windows)

### ISSUE THREAD

**Issue by gjnardoni** [valiant1x/intensecoinwallet#4]
Hello.
Wallet compilation just run fine but when I try to launch the wallet it loads the .exe and exit without showing any error.
Could you please tell me which is your environment?
I tried VS2015 Windows 7/10, QT 5.8.0 and 5.9.1/2 with VS and with QTCreator, same happens.

Thanks in advance.-

**Comment by valiant1x** [comment]
Hi,

Make sure the output/build folder has the proper Qt dependencies adjacent to the binary. Check out the posted releases to see which DLLs are required, and also note that the `platform\qwindows.dll` dependency is required.
