### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by Staz1st** [valiant1x/intensecoinwallet#43]
installed intensecoin-gui-win64-v201 to create a new wallet. Syncing stops when there's 11258 blocks left.
Any suggestions?
![syncerror](https://user-images.githubusercontent.com/35668621/39411208-c9103e20-4c05-11e8-8bc4-5bf967457ec5.jpg)

**Comment by mtl1979** [comment]
Update to 2.0.2 ... It should fix most of the sync issues... From the screenshot it's obvious the daemon is trying to download blocks right after the hard fork height.
