### ISSUE TITLE
Mainnet only 93.8% of complete blockchain?

### ISSUE THREAD

**Issue by R00dNet** [valiant1x/intensecoinwallet#44]
fresh install synchronization starts no porblem. Once the message "LMDB Mapsize increased. Old: 7199MiB, New 9018MiB appears daemon will not go past 93.8% sync, stuck around block 11133. 15 days behind.

**Comment by R00dNet** [comment]
nevermind. restarting daemon when this happens seems to kick start sync again.

**Comment by R00dNet** [comment]
nevermind. restarting daemon when this happens seems to kick start sync again.

**Comment by mtl1979** [comment]
Block 11133 is nowhere near 15 days behind... Current block height is 179151 as of creation time of this comment.

**Comment by R00dNet** [comment]
been waiting on new update. will let you know when get chance to install 2.0.2.1, thx for reply.

**Comment by R00dNet** [comment]
@valiant1x is sycning to full blockchain it appears. past blocksize previous wallet would not. I am having to restart daemon a few times as it hangs now and then.
