### ISSUE TITLE
Lookup error from release download

### ISSUE THREAD

**Issue by mbatini** [valiant1x/intensecoinwallet#49]
Download of https://github.com/valiant1x/intensecoinwallet/releases/latest (linux 64) gives:

mbatini@mb460:/opt/intensecoin$ ./start-gui.sh 
./intensecoin-wallet-gui: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds

I'm on Ubuntu 17.10

**Comment by expociti** [comment]
same here on ubuntu 18

**Comment by pallas1** [comment]
Please try the updated linux gui build

**Comment by pallas1** [comment]
Closing as inactive, please reopen if needed.
