### ISSUE TITLE
"GoToMyPC" crashed the wallet

### ISSUE THREAD

**Issue by tonyxia2016** [valiant1x/intensecoinwallet#57]
So I may have found an odd ITNS wallet bug.

When I remote into the PC that has my wallet with "GoToMyPC" at any point... when I return to the computer with the wallet it (the wallet) has closed.

This happens 100% of the time -- so I assume it is incompatible in some way.

Not a HUGE deal but figured I would report it.

Note: copied from https://bitcointalk.org/index.php?topic=2090765.new#new

**Comment by valiant1x** [comment]
Not a typical use case so I am not sure we will be investigating a resolution. Could be more of an issue with the way GoToMyPC is hooking windows/video than something related to our wallet. For now, labeling wontfix - we can re-evaluate if this becomes more prevalent.
