### ISSUE TITLE
QT Application Color Scheme Not Respected

### ISSUE THREAD

**Issue by MatthewCroughan** [valiant1x/intensecoinwallet#6]
For example, when selecting a darker color scheme like Zion or Breeze Dark in a desktop like KDE, the font colors within the application are also changed, despite the wallet not being entirely themable, which produces unreadable contrast with white on white text. This extends to other color schemes too, though the effects aren't as bad as it is with a darker theme.

![pasted_image_at_2017_11_16_04_00_pm](https://user-images.githubusercontent.com/26458780/33232675-1b77bcf2-d202-11e7-819f-92c3e597234f.png)

**Comment by pallas1** [comment]
Closing this as it relates to the old, obsolete gui.
If you experience a similar issue with the newer one, please open a new issue. Thanks.
