### ISSUE TITLE
missing libs in linux build

### ISSUE THREAD

**Issue by iedemam** [valiant1x/intensecoinwallet#63]

**Comment by iedemam** [comment]
Summary of artifact differences: [build.diff.txt](https://github.com/valiant1x/intensecoinwallet/files/2185042/build.diff.txt)

**Comment by iedemam** [comment]
User note: "Runing LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' ./start-gui.sh solves this issue."

**Comment by pallas1** [comment]
not sure it's the same issue, as I don't see how that could solve missing qt plugins

**Comment by iedemam** [comment]
I think I need specific details on which libs are missing. A lot of the "missing" libs do not seem related to the project and would be bloat in the end.

**Comment by pallas1** [comment]
qrc:///main.qml:34 module "Qt.labs.settings" is not installed

this and possibly others.

**Comment by iedemam** [comment]
This has been fixed and will be delivered in the next release.
