### ISSUE TITLE
Version 1.4.1 stopped syncing at height 71678

### ISSUE THREAD

**Issue by mtl1979** [valiant1x/intensecoinwallet#7]
Something in 1.4.1 wallet caused sync failure at height 71678 and the blockchain did split.

**Comment by valiant1x** [comment]
If you are experiencing any kind of sync abnormalities in 1.4.1, as far as we know this is due to using 1.4.0 at some point which caused incorrect difficulty calculations for blocks.

Did you use 1.4.0?

Have you tried restarting the wallet? How about re-syncing the blockchain?

**Comment by mtl1979** [comment]
Deleted the whole blockchain directory after each upgrade. Started with 1.2.2, then upgraded to 1.3.0 and finally to 1.4.1. Dunno if had anything to do with main pool going on a fork, but everything was quiet for 30 minutes and really slow after that. The log was full of rejected transactions and warnings about double spending. Pretty much every connection did drop due to warning flood.

**Comment by valiant1x** [comment]
So the wallet is no longer stopped syncing?

Things slowed down at that block because the main pool forked and the main pool was responsible for producing the vast majority of the blocks on the network. Therefore, when the main pool stopped producing them, the block time slowed down dramatically.

**Comment by mtl1979** [comment]
@valiant1x It took ten hours after the main pool was back online before it synced correctly again.

**Comment by valiant1x** [comment]
Understood, thanks for the update. I'll close this for now then as it seems all the issues were related to a transient side chain.
